In [ ]:
#import torch library and neural network module
import torch 
import torch.nn as nn

In [2]:
#Create a inputs as tensor(random input)
inputs = torch.tensor([3.0,1.0,-2.0])




Assign inputs to the neuron

In [3]:
#Create a neuron
neuron = nn.Linear(in_features=3, out_features=1)
output = neuron(inputs)

In [4]:
print(output)

tensor([1.7594], grad_fn=<ViewBackward0>)


In [5]:
print(neuron.weight)
print(neuron.bias)

Parameter containing:
tensor([[ 0.2400, -0.0698, -0.5307]], requires_grad=True)
Parameter containing:
tensor([0.0477], requires_grad=True)


In [6]:
neuron.weight @ inputs.T + neuron.bias

C:\Users\dell\AppData\Local\Temp\ipykernel_17212\2087955816.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4484.)
  neuron.weight @ inputs.T + neuron.bias


tensor([1.7594], grad_fn=<AddBackward0>)